---
title: "Final Project - Step 2 - Week 10"
output: html_document
date: '2022-05-11'
---


### Data importing and cleaning steps are explained in the text and follow a logical process.  Outline your data preparation and cleansing steps.

Filter only USA to make it easier to analyze than the entire world.




### With a clean dataset, show what the final data set looks like. However, do not print off a data frame with 200+ rows; show me the data in the most condensed form possible.

```{r data1}
setwd("/Users/marianamacdonald/Documents/DATA SCIENCE/DSC 520/Statistics R/Week 2/dsc520")
library(readxl)
DATA1 <- read_excel("DATA 1 - Final Project - Mental health Depression disorder Data.xlsx")
head(DATA1)
```


### What do you not know how to do right now that you need to learn to import and cleanup your dataset?



### Discuss how you plan to uncover new information in the data that is not self-evident.




### What are different ways you could look at this data to answer the questions you want to answer?



### Do you plan to slice and dice the data in different ways, create new variables, or join separate data frames to create new summary information? Explain.




### How could you summarize your data to answer key questions?




### What types of plots and tables will help you to illustrate the findings to your questions? Ensure that all graph plots have axis titles, legend if necessary, scales are appropriate, appropriate geoms used, etc.).





### What do you not know how to do right now that you need to learn to answer your questions?




### Do you plan on incorporating any machine learning techniques to answer your research questions? Explain.




